[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  # Pro plan allows up to 26 seconds timeout
  timeout = 10

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"

